# Generated by Django 5.0.6 on 2024-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaylistData",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("key", models.IntegerField()),
                ("loudness", models.FloatField()),
                ("mode", models.IntegerField()),
                ("acousticness", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("liveness", models.FloatField()),
                ("valence", models.FloatField()),
                ("tempo", models.FloatField()),
                ("duration_ms", models.IntegerField()),
                ("time_signature", models.IntegerField()),
                ("num_bars", models.IntegerField()),
                ("num_sections", models.IntegerField()),
                ("num_segments", models.IntegerField()),
                ("class_field", models.IntegerField()),
                ("star_rating", models.FloatField(null=True)),
            ],
        ),
    ]
